# Form implementation generated from reading ui file './qt6_test/main_v2.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 612)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.upTCPPosButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.upTCPPosButton.setMinimumSize(QtCore.QSize(70, 70))
        self.upTCPPosButton.setMaximumSize(QtCore.QSize(70, 70))
        self.upTCPPosButton.setStyleSheet("border-image: url(:/move-content/norm-up.png);\n"
"\n"
"")
        self.upTCPPosButton.setText("")
        self.upTCPPosButton.setObjectName("upTCPPosButton")
        self.horizontalLayout_24.addWidget(self.upTCPPosButton)
        self.downTCPPosButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.downTCPPosButton.setMinimumSize(QtCore.QSize(70, 70))
        self.downTCPPosButton.setMaximumSize(QtCore.QSize(70, 70))
        self.downTCPPosButton.setStyleSheet("border-image: url(:/move-content/norm-down.png)")
        self.downTCPPosButton.setText("")
        self.downTCPPosButton.setObjectName("downTCPPosButton")
        self.horizontalLayout_24.addWidget(self.downTCPPosButton)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.skewedUpButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.skewedUpButton.setMinimumSize(QtCore.QSize(71, 51))
        self.skewedUpButton.setMaximumSize(QtCore.QSize(71, 51))
        self.skewedUpButton.setStyleSheet("border-image: url(:/move-content/skewed-up.png)")
        self.skewedUpButton.setText("")
        self.skewedUpButton.setObjectName("skewedUpButton")
        self.gridLayout_2.addWidget(self.skewedUpButton, 0, 1, 1, 1)
        self.skewedLeft = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.skewedLeft.setMinimumSize(QtCore.QSize(71, 51))
        self.skewedLeft.setMaximumSize(QtCore.QSize(71, 51))
        self.skewedLeft.setStyleSheet("border-image: url(:/move-content/skewed-left.png)")
        self.skewedLeft.setText("")
        self.skewedLeft.setObjectName("skewedLeft")
        self.gridLayout_2.addWidget(self.skewedLeft, 1, 0, 1, 1)
        self.skewedRightButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.skewedRightButton.setMinimumSize(QtCore.QSize(71, 51))
        self.skewedRightButton.setMaximumSize(QtCore.QSize(71, 51))
        self.skewedRightButton.setStyleSheet("border-image: url(:/move-content/skewed-right.png)")
        self.skewedRightButton.setText("")
        self.skewedRightButton.setObjectName("skewedRightButton")
        self.gridLayout_2.addWidget(self.skewedRightButton, 1, 2, 1, 1)
        self.skewedDownButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.skewedDownButton.setMinimumSize(QtCore.QSize(71, 51))
        self.skewedDownButton.setMaximumSize(QtCore.QSize(71, 51))
        self.skewedDownButton.setStyleSheet("border-image : url(:/move-content/skewed-down.png)")
        self.skewedDownButton.setText("")
        self.skewedDownButton.setObjectName("skewedDownButton")
        self.gridLayout_2.addWidget(self.skewedDownButton, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.turnLeftButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.turnLeftButton.setMinimumSize(QtCore.QSize(90, 70))
        self.turnLeftButton.setMaximumSize(QtCore.QSize(90, 70))
        self.turnLeftButton.setStyleSheet("border-image: url(:/move-content/turn-left.png)")
        self.turnLeftButton.setText("")
        self.turnLeftButton.setObjectName("turnLeftButton")
        self.horizontalLayout_25.addWidget(self.turnLeftButton)
        self.turnRightButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.turnRightButton.setMinimumSize(QtCore.QSize(90, 70))
        self.turnRightButton.setMaximumSize(QtCore.QSize(90, 70))
        self.turnRightButton.setStyleSheet("border-image : url(:/move-content/turn-right.png)")
        self.turnRightButton.setText("")
        self.turnRightButton.setObjectName("turnRightButton")
        self.horizontalLayout_25.addWidget(self.turnRightButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bentUpButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.bentUpButton.setMinimumSize(QtCore.QSize(71, 51))
        self.bentUpButton.setMaximumSize(QtCore.QSize(71, 51))
        self.bentUpButton.setStyleSheet("border-image: url(:/bottom/bent-up.png)")
        self.bentUpButton.setText("")
        self.bentUpButton.setObjectName("bentUpButton")
        self.gridLayout_3.addWidget(self.bentUpButton, 0, 1, 1, 1)
        self.bentLeftButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.bentLeftButton.setMinimumSize(QtCore.QSize(71, 51))
        self.bentLeftButton.setMaximumSize(QtCore.QSize(71, 51))
        self.bentLeftButton.setStyleSheet("border-image: url(:/bottom/bent-left.png)")
        self.bentLeftButton.setText("")
        self.bentLeftButton.setObjectName("bentLeftButton")
        self.gridLayout_3.addWidget(self.bentLeftButton, 1, 0, 1, 1)
        self.bentRightButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.bentRightButton.setMinimumSize(QtCore.QSize(71, 51))
        self.bentRightButton.setMaximumSize(QtCore.QSize(71, 51))
        self.bentRightButton.setStyleSheet("border-image: url(:/bottom/bent-right.png)")
        self.bentRightButton.setText("")
        self.bentRightButton.setObjectName("bentRightButton")
        self.gridLayout_3.addWidget(self.bentRightButton, 1, 2, 1, 1)
        self.bentBottomButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.bentBottomButton.setMinimumSize(QtCore.QSize(71, 51))
        self.bentBottomButton.setMaximumSize(QtCore.QSize(71, 51))
        self.bentBottomButton.setStyleSheet("border-image: url(:/bottom/bent-down.png)")
        self.bentBottomButton.setText("")
        self.bentBottomButton.setObjectName("bentBottomButton")
        self.gridLayout_3.addWidget(self.bentBottomButton, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.horizontalLayout_29.addLayout(self.gridLayout_7)
        self.robotWIdget = QtWidgets.QWidget(parent=self.centralwidget)
        self.robotWIdget.setObjectName("robotWIdget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.robotWIdget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_25 = QtWidgets.QLabel(parent=self.robotWIdget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_14.addWidget(self.label_25)
        self.featureComboBox = QtWidgets.QComboBox(parent=self.robotWIdget)
        self.featureComboBox.setObjectName("featureComboBox")
        self.featureComboBox.addItem("")
        self.featureComboBox.addItem("")
        self.featureComboBox.addItem("")
        self.verticalLayout_14.addWidget(self.featureComboBox)
        self.horizontalLayout_28.addLayout(self.verticalLayout_14)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_26 = QtWidgets.QLabel(parent=self.robotWIdget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_15.addWidget(self.label_26)
        self.activeTCPLineEdit = QtWidgets.QLineEdit(parent=self.robotWIdget)
        self.activeTCPLineEdit.setObjectName("activeTCPLineEdit")
        self.verticalLayout_15.addWidget(self.activeTCPLineEdit)
        self.horizontalLayout_28.addLayout(self.verticalLayout_15)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame = QtWidgets.QFrame(parent=self.robotWIdget)
        self.frame.setMinimumSize(QtCore.QSize(500, 500))
        self.frame.setMaximumSize(QtCore.QSize(500, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_26.addWidget(self.frame)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.zoomInButton = QtWidgets.QPushButton(parent=self.robotWIdget)
        self.zoomInButton.setMinimumSize(QtCore.QSize(20, 20))
        self.zoomInButton.setMaximumSize(QtCore.QSize(20, 20))
        self.zoomInButton.setStyleSheet("border : 1px solid black;\n"
"\n"
"border-image : url(:/robot-panel/plus.png);\n"
"padding: 2px;\n"
"\n"
"")
        self.zoomInButton.setText("")
        self.zoomInButton.setObjectName("zoomInButton")
        self.verticalLayout_13.addWidget(self.zoomInButton)
        self.verticalSlider = QtWidgets.QSlider(parent=self.robotWIdget)
        self.verticalSlider.setMinimumSize(QtCore.QSize(20, 300))
        self.verticalSlider.setMaximumSize(QtCore.QSize(30, 400))
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayout_13.addWidget(self.verticalSlider)
        self.zoomOutButton = QtWidgets.QPushButton(parent=self.robotWIdget)
        self.zoomOutButton.setMinimumSize(QtCore.QSize(20, 20))
        self.zoomOutButton.setMaximumSize(QtCore.QSize(20, 20))
        self.zoomOutButton.setStyleSheet("border : 1px solid black;\n"
"\n"
"border-image : url(:/robot-panel/minus.png);\n"
"padding: 2px;\n"
"\n"
"")
        self.zoomOutButton.setText("")
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.verticalLayout_13.addWidget(self.zoomOutButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_26.addLayout(self.verticalLayout_13)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.homeButton = QtWidgets.QPushButton(parent=self.robotWIdget)
        self.homeButton.setMinimumSize(QtCore.QSize(124, 30))
        self.homeButton.setStyleSheet("#homeButton:hover{\n"
"    border : 1px solid blue;\n"
"}\n"
"")
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout_27.addWidget(self.homeButton)
        self.freedriveButton = QtWidgets.QPushButton(parent=self.robotWIdget)
        self.freedriveButton.setMinimumSize(QtCore.QSize(124, 30))
        self.freedriveButton.setStyleSheet("#freedriveButton:hover{\n"
"    border : 1px solid blue;\n"
"}\n"
"")
        self.freedriveButton.setObjectName("freedriveButton")
        self.horizontalLayout_27.addWidget(self.freedriveButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.gridLayout_4.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_29.addWidget(self.robotWIdget)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(360, 160))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.xToolLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.xToolLineEdit.setObjectName("xToolLineEdit")
        self.horizontalLayout_17.addWidget(self.xToolLineEdit)
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.yToolLIneEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.yToolLIneEdit.setObjectName("yToolLIneEdit")
        self.horizontalLayout_18.addWidget(self.yToolLIneEdit)
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.zToolLIneEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.zToolLIneEdit.setObjectName("zToolLIneEdit")
        self.horizontalLayout_19.addWidget(self.zToolLIneEdit)
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.rxToolLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.rxToolLineEdit.setObjectName("rxToolLineEdit")
        self.horizontalLayout_20.addWidget(self.rxToolLineEdit)
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_20.addWidget(self.label_22)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.ryToolLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.ryToolLineEdit.setObjectName("ryToolLineEdit")
        self.horizontalLayout_21.addWidget(self.ryToolLineEdit)
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.rzToolLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.rzToolLineEdit.setObjectName("rzToolLineEdit")
        self.horizontalLayout_22.addWidget(self.rzToolLineEdit)
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_22.addWidget(self.label_24)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 32, 344, 404))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.baseLeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.baseLeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.baseLeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.baseLeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.baseLeftButton.setText("")
        self.baseLeftButton.setObjectName("baseLeftButton")
        self.horizontalLayout_5.addWidget(self.baseLeftButton)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.bLineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.bLineEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.bLineEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.bLineEdit.setObjectName("bLineEdit")
        self.horizontalLayout_5.addWidget(self.bLineEdit)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(10, 30))
        self.label_7.setMaximumSize(QtCore.QSize(10, 30))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.baseRightButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.baseRightButton.setMinimumSize(QtCore.QSize(20, 20))
        self.baseRightButton.setMaximumSize(QtCore.QSize(30, 30))
        self.baseRightButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.baseRightButton.setText("")
        self.baseRightButton.setObjectName("baseRightButton")
        self.horizontalLayout_5.addWidget(self.baseRightButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.baseJointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.baseJointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.baseJointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.baseJointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 4px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.baseJointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.baseJointSlider.setObjectName("baseJointSlider")
        self.horizontalLayout_6.addWidget(self.baseJointSlider)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.elbowLeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.elbowLeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.elbowLeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.elbowLeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.elbowLeftButton.setText("")
        self.elbowLeftButton.setObjectName("elbowLeftButton")
        self.horizontalLayout_7.addWidget(self.elbowLeftButton)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.eLineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.eLineEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.eLineEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.eLineEdit.setObjectName("eLineEdit")
        self.horizontalLayout_7.addWidget(self.eLineEdit)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(10, 0))
        self.label_8.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.elbowRightButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.elbowRightButton.setMinimumSize(QtCore.QSize(30, 30))
        self.elbowRightButton.setMaximumSize(QtCore.QSize(30, 30))
        self.elbowRightButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.elbowRightButton.setText("")
        self.elbowRightButton.setObjectName("elbowRightButton")
        self.horizontalLayout_7.addWidget(self.elbowRightButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.elbowJointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.elbowJointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.elbowJointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.elbowJointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.elbowJointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.elbowJointSlider.setObjectName("elbowJointSlider")
        self.horizontalLayout_8.addWidget(self.elbowJointSlider)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.shoulderLeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.shoulderLeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.shoulderLeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.shoulderLeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.shoulderLeftButton.setText("")
        self.shoulderLeftButton.setObjectName("shoulderLeftButton")
        self.horizontalLayout_10.addWidget(self.shoulderLeftButton)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        spacerItem9 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.sLineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.sLineEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.sLineEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.sLineEdit.setObjectName("sLineEdit")
        self.horizontalLayout_10.addWidget(self.sLineEdit)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.shoulderRightButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.shoulderRightButton.setMinimumSize(QtCore.QSize(30, 30))
        self.shoulderRightButton.setMaximumSize(QtCore.QSize(30, 30))
        self.shoulderRightButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.shoulderRightButton.setText("")
        self.shoulderRightButton.setObjectName("shoulderRightButton")
        self.horizontalLayout_10.addWidget(self.shoulderRightButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.shulderJointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.shulderJointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.shulderJointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.shulderJointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.shulderJointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.shulderJointSlider.setObjectName("shulderJointSlider")
        self.horizontalLayout_9.addWidget(self.shulderJointSlider)
        spacerItem11 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.w1LeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w1LeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w1LeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w1LeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.w1LeftButton.setText("")
        self.w1LeftButton.setObjectName("w1LeftButton")
        self.horizontalLayout_11.addWidget(self.w1LeftButton)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        spacerItem12 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.w1LineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.w1LineEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.w1LineEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.w1LineEdit.setObjectName("w1LineEdit")
        self.horizontalLayout_11.addWidget(self.w1LineEdit)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.w1RightButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w1RightButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w1RightButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w1RightButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.w1RightButton.setText("")
        self.w1RightButton.setObjectName("w1RightButton")
        self.horizontalLayout_11.addWidget(self.w1RightButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem13 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.wrist1JointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.wrist1JointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.wrist1JointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.wrist1JointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.wrist1JointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.wrist1JointSlider.setObjectName("wrist1JointSlider")
        self.horizontalLayout_12.addWidget(self.wrist1JointSlider)
        spacerItem14 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.w2LeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w2LeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w2LeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w2LeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.w2LeftButton.setText("")
        self.w2LeftButton.setObjectName("w2LeftButton")
        self.horizontalLayout_13.addWidget(self.w2LeftButton)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        spacerItem15 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.w2LineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.w2LineEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.w2LineEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.w2LineEdit.setObjectName("w2LineEdit")
        self.horizontalLayout_13.addWidget(self.w2LineEdit)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(10, 0))
        self.label_11.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.w2RightButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w2RightButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w2RightButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w2RightButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.w2RightButton.setText("")
        self.w2RightButton.setObjectName("w2RightButton")
        self.horizontalLayout_13.addWidget(self.w2RightButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem16 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.wrist2JointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.wrist2JointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.wrist2JointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.wrist2JointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.wrist2JointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.wrist2JointSlider.setObjectName("wrist2JointSlider")
        self.horizontalLayout_14.addWidget(self.wrist2JointSlider)
        spacerItem17 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.w3LeftButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w3LeftButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w3LeftButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w3LeftButton.setStyleSheet("border-image: url(:/move-content/left.svg)")
        self.w3LeftButton.setText("")
        self.w3LeftButton.setObjectName("w3LeftButton")
        self.horizontalLayout_15.addWidget(self.w3LeftButton)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        spacerItem18 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.w3LIneEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.w3LIneEdit.setMinimumSize(QtCore.QSize(61, 21))
        self.w3LIneEdit.setMaximumSize(QtCore.QSize(61, 21))
        self.w3LIneEdit.setObjectName("w3LIneEdit")
        self.horizontalLayout_15.addWidget(self.w3LIneEdit)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(10, 0))
        self.label_10.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.w3RIghtButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.w3RIghtButton.setMinimumSize(QtCore.QSize(30, 30))
        self.w3RIghtButton.setMaximumSize(QtCore.QSize(30, 30))
        self.w3RIghtButton.setStyleSheet("border-image : url(:/move-content/right.svg);")
        self.w3RIghtButton.setText("")
        self.w3RIghtButton.setObjectName("w3RIghtButton")
        self.horizontalLayout_15.addWidget(self.w3RIghtButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem19 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.wrist3JointSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.wrist3JointSlider.setMinimumSize(QtCore.QSize(200, 4))
        self.wrist3JointSlider.setMaximumSize(QtCore.QSize(800, 16))
        self.wrist3JointSlider.setStyleSheet("::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 18px; \n"
"    margin: 2px 0;\n"
"\n"
"}\n"
"::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    margin : 0 -3px;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"::sub-page:horizontal {\n"
"    background: white;\n"
"}")
        self.wrist3JointSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.wrist3JointSlider.setObjectName("wrist3JointSlider")
        self.horizontalLayout_16.addWidget(self.wrist3JointSlider)
        spacerItem20 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.horizontalLayout_29.addLayout(self.verticalLayout_12)
        self.verticalLayout_17.addLayout(self.horizontalLayout_29)
        self.bottomFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottomFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.bottomFrame.setStyleSheet("#bottomFrame{\n"
"    background-color : #333333;\n"
"}\n"
"#bottomFrame > *{\n"
"    color: white;\n"
"}")
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottomFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.initPushButton = QtWidgets.QPushButton(parent=self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initPushButton.sizePolicy().hasHeightForWidth())
        self.initPushButton.setSizePolicy(sizePolicy)
        self.initPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.initPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.initPushButton.setStyleSheet("#initPushButton {\n"
"\n"
"    border: 4px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: #00bd00;\n"
"    padding: 5px;\n"
"}\n"
"#initPushButton:checked{\n"
"    background-color: #ff0000;\n"
"}")
        self.initPushButton.setText("")
        self.initPushButton.setCheckable(True)
        self.initPushButton.setObjectName("initPushButton")
        self.horizontalLayout_3.addWidget(self.initPushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem21 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.speedLabel = QtWidgets.QLabel(parent=self.bottomFrame)
        self.speedLabel.setStyleSheet("color: white;")
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout.addWidget(self.speedLabel)
        self.speedSlider = QtWidgets.QSlider(parent=self.bottomFrame)
        self.speedSlider.setMinimumSize(QtCore.QSize(200, 0))
        self.speedSlider.setBaseSize(QtCore.QSize(100, 0))
        self.speedSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout.addWidget(self.speedSlider)
        self.speedValueLabel = QtWidgets.QLabel(parent=self.bottomFrame)
        self.speedValueLabel.setStyleSheet("color : white;\n"
"")
        self.speedValueLabel.setObjectName("speedValueLabel")
        self.horizontalLayout.addWidget(self.speedValueLabel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem22 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem22)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playPushButton = QtWidgets.QPushButton(parent=self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPushButton.sizePolicy().hasHeightForWidth())
        self.playPushButton.setSizePolicy(sizePolicy)
        self.playPushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.playPushButton.setStyleSheet("#playPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-image: url(:/bottom/play.png) 0 0 0 0 stretch stretch;\n"
"    padding: 5px;\n"
"}\n"
"#playPushButton:checked{\n"
"    border-image: url(:/bottom/play-gray.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.playPushButton.setText("")
        self.playPushButton.setCheckable(True)
        self.playPushButton.setObjectName("playPushButton")
        self.horizontalLayout_2.addWidget(self.playPushButton)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.fwdPushButton = QtWidgets.QPushButton(parent=self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwdPushButton.sizePolicy().hasHeightForWidth())
        self.fwdPushButton.setSizePolicy(sizePolicy)
        self.fwdPushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.fwdPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.fwdPushButton.setStyleSheet("\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-image: url(:/bottom/forward.jpeg) 0 0 0 0 stretch stretch;\n"
"    padding: 5px;\n"
"\n"
"")
        self.fwdPushButton.setText("")
        self.fwdPushButton.setCheckable(True)
        self.fwdPushButton.setObjectName("fwdPushButton")
        self.horizontalLayout_2.addWidget(self.fwdPushButton)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem24)
        self.stopPushButton = QtWidgets.QPushButton(parent=self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopPushButton.sizePolicy().hasHeightForWidth())
        self.stopPushButton.setSizePolicy(sizePolicy)
        self.stopPushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.stopPushButton.setStyleSheet("#stopPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-image: url(:/bottom/stop.png) 0 0 0 0 stretch stretch;\n"
"    padding: 5px;\n"
"}\n"
"#stopPushButton:checked{\n"
"    border-image: url(:/bottom/stop-gray.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.stopPushButton.setText("")
        self.stopPushButton.setCheckable(True)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_2.addWidget(self.stopPushButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem25 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.dateTimeVLayout = QtWidgets.QVBoxLayout()
        self.dateTimeVLayout.setObjectName("dateTimeVLayout")
        self.timeLabel = QtWidgets.QLabel(parent=self.bottomFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: white;\n"
"")
        self.timeLabel.setObjectName("timeLabel")
        self.dateTimeVLayout.addWidget(self.timeLabel)
        self.dateLabel = QtWidgets.QLabel(parent=self.bottomFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color: white;")
        self.dateLabel.setObjectName("dateLabel")
        self.dateTimeVLayout.addWidget(self.dateLabel)
        self.horizontalLayout_3.addLayout(self.dateTimeVLayout)
        spacerItem26 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.powerPushButton = QtWidgets.QPushButton(parent=self.bottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerPushButton.sizePolicy().hasHeightForWidth())
        self.powerPushButton.setSizePolicy(sizePolicy)
        self.powerPushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.powerPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.powerPushButton.setStyleSheet("#powerPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-image: url(:/bottom/power.png) 0 0 0 0 stretch stretch;\n"
"    padding: 5px;\n"
"}\n"
"#powerPushButton:checked{\n"
"    border-image: url(:/bottom/power-gray.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.powerPushButton.setText("")
        self.powerPushButton.setCheckable(True)
        self.powerPushButton.setChecked(False)
        self.powerPushButton.setObjectName("powerPushButton")
        self.horizontalLayout_3.addWidget(self.powerPushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_17.addWidget(self.bottomFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "TCP Position"))
        self.groupBox_4.setTitle(_translate("MainWindow", "TCP Orientation"))
        self.label_25.setText(_translate("MainWindow", "Feature"))
        self.featureComboBox.setItemText(0, _translate("MainWindow", "View"))
        self.featureComboBox.setItemText(1, _translate("MainWindow", "TCP"))
        self.featureComboBox.setItemText(2, _translate("MainWindow", "Base"))
        self.label_26.setText(_translate("MainWindow", "Active TCP"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.freedriveButton.setText(_translate("MainWindow", "Freedrive"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tool Position"))
        self.label_13.setText(_translate("MainWindow", "X"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.label_14.setText(_translate("MainWindow", "Y"))
        self.label_17.setText(_translate("MainWindow", "mm"))
        self.label_15.setText(_translate("MainWindow", "Z"))
        self.label_18.setText(_translate("MainWindow", "mm"))
        self.label_19.setText(_translate("MainWindow", "RX"))
        self.label_22.setText(_translate("MainWindow", "rad"))
        self.label_20.setText(_translate("MainWindow", "RY"))
        self.label_23.setText(_translate("MainWindow", "rad"))
        self.label_21.setText(_translate("MainWindow", "RZ"))
        self.label_24.setText(_translate("MainWindow", "rad"))
        self.groupBox.setTitle(_translate("MainWindow", "Joint Position"))
        self.label.setText(_translate("MainWindow", "Base"))
        self.label_7.setText(_translate("MainWindow", "°"))
        self.label_3.setText(_translate("MainWindow", "Elbow"))
        self.label_8.setText(_translate("MainWindow", "°"))
        self.label_2.setText(_translate("MainWindow", "Shoulder"))
        self.label_12.setText(_translate("MainWindow", "°"))
        self.label_4.setText(_translate("MainWindow", "Wrist 1"))
        self.label_9.setText(_translate("MainWindow", "°"))
        self.label_5.setText(_translate("MainWindow", "Wrist 2"))
        self.label_11.setText(_translate("MainWindow", "°"))
        self.label_6.setText(_translate("MainWindow", "Wrist 3"))
        self.label_10.setText(_translate("MainWindow", "°"))
        self.speedLabel.setText(_translate("MainWindow", "Speed"))
        self.speedValueLabel.setText(_translate("MainWindow", "100%"))
        self.timeLabel.setText(_translate("MainWindow", "24:59:59"))
        self.dateLabel.setText(_translate("MainWindow", "December 31,2024"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
